更新ing
SlimeTraditionalTranslation/SfChunkInfo pull request #7
Opened 2023-01-20 07:22 UTC by xwinhyukx

2023-01-20 09:43 UTC, xMikux requested changes

2023-01-20 09:43 UTC, xMikux commented on README.md
> +一個簡單方便的掃描器, 用於掃描黏液科技在一格區塊中,它還測量用於區塊功能的使用率情況.
```suggestion
一個簡單方便的掃描器, 用於掃描每格區塊中的黏液科技方塊, 它同時也能測量方塊的能源使用情況.
```

2023-01-20 19:29 UTC, xMikux approved these changes

2023-01-21 14:15 UTC, weiii-joe approved these changes

2023-01-21 14:15 UTC, merged